### ISSUE TITLE
是否介意将本项目代码直接拷贝到其它项目？

### ISSUE THREAD

**Issue by LuoZijun** [citahub/libsm#16]
Hi，想问下作者是否介意我将本项目的代码直接拷贝到其它项目呢（应该不会有什么太大的修改）？

https://github.com/LuoZijun/crypto

**Comment by rink1969** [comment]
可以的。
只要按照Apache开源协议，保留我们的License声明即可。
如果后续有修改，请在文件头下增加修改记录，声明你自己修改的部分。
