### ISSUE TITLE
sm2还没有实现非对称加密解密么？

### ISSUE THREAD

**Issue by gaojunjie03** [citahub/libsm#20]
sm2还没有实现非对称加密解密么？ 我看现在好像只能进行数字签名？
有加密解密方案或文档么？

**Comment by tzxun** [comment]
因为是给区块链用，所以这个库没实现加解密。文档见这个 https://www.oscca.gov.cn/sca/xxgk/2010-12/17/1002386/files/b791a9f908bb4803875ab6aeeb7b4e03.pdf

**Comment by Pencil-Yao** [comment]
目前确实还没有这个功能，不过这个功能较为简单，我开个 issue 后续考虑实现

**Comment by Pencil-Yao** [comment]
https://github.com/citahub/libsm/issues/23
