### ISSUE TITLE
ecc曲线point add 和point double 计算结果不同

### ISSUE THREAD

**Issue by FullyRobert** [citahub/libsm#22]
我尝试为sm2算法中的ecc.rs代码内，为测试test_add_double_neg增加以下测试，该测试希望验证点加法和点倍增的结果是否相同：
``` rust
        let double_g = curve.double(&g);  //  2 * g
        let add_g = curve.add(&g,&g);     // g + g
        assert!(curve.eq(&add_g,&double_g));
```
但是测试结果告诉我没有通过测试：
```
thread 'sm2::ecc::tests::test_add_double_neg' panicked at 'assertion failed: curve.eq(&add_g, &double_g)', src\sm2\ecc.rs:595:
```
~~查看了一下实现点加法和点倍增的算法，发现算法和我之前学习的算法有所出入。例如，点倍增算法中引入了参数a：~~
~~而论文中实现点倍增并没有参数a的参与（雅可比坐标系下）~~
经过学习，了解到此处点倍增利用的似乎是dbl-1998-cmo-2中的方法，抱歉。点加法似乎是使用了add-2007-bl中的算法？

想请问点加法和点倍增计算结果为何不一致的原因，以及计算点加法和点乘法时使用到的算法名称。个人水平有限，难免在理解上会出现错误，烦请多多指教

**Comment by Pencil-Yao** [comment]
感谢您的反馈，关于 `libsm` 中用的 point_add 用的算法是 `add-1998-cmo-2`, 然后出现上述错误的原因也是这个加法不支持完全相同的两个点的点加, 正常情况完全相同的两个点的点加应该退化为点平方运算, 但在 `libsm` 中把相关代码注释掉了.
https://github.com/citahub/libsm/blob/66562196c3aa6a2f3db6fbf21e593521eadc2ae7/src/sm2/ecc.rs#L298-L309
而至于为何不相等的原因是雅可比坐标系中相同的仿射点可以有多个不同的映射点, `test_add_double_neg` 这个用例确实容易让人感到误解

**Comment by Pencil-Yao** [comment]
https://github.com/citahub/libsm/pull/24

**Comment by FullyRobert** [comment]
非常感谢您的解答，这两天我进行了一些point_add和point_double的优化尝试，发现libsm中的使用的add-1998-cmo-2和dbl-1998-cmo-2存在一些额外的开销，可以进行优化：例如，在点加法中，存在一些立方操作可以进行优化。
根据 http://hyperelliptic.org/EFD/g1p/auto-shortw-jacobian.html#addition-add-1998-cmo-2 中的算法，我认为目前使用的算法更接近于add-1998-cmo而不是add-1998-cmo-2。在完整实现了add-1998-cmo-2和dbl-1998-cmo-2后，加法的速度提高了30%，点倍增速度提高了约8%，整体签名/验签速度提升了12%。如果您认为这样的优化有意义，我可以提交一个pr来更新它。

此处附上新加法的代码，相较于原算法减少了3次立方操作：
``` rust
        let ctx = &self.fctx;

        let z1z1 = ctx.square(&p1.z);
        let z2z2 = ctx.square(&p2.z);
        let u1 = ctx.mul(&p1.x,&z2z2);
        let u2 = ctx.mul(&p2.x,&z1z1);
        let s1 = ctx.mul(&p1.y,&ctx.mul(&p2.z,&z2z2));
        let s2 = ctx.mul(&p2.y,&ctx.mul(&p1.z,&z1z1));

        let h = ctx.sub(&u2,&u1);
        let hh = ctx.square(&h);
        let hhh = ctx.mul(&h,&hh);
        let r = ctx.sub(&s2,&s1);
        let v = ctx.mul(&u1,&hh);

        let x3 = ctx.sub(&ctx.sub(&ctx.square(&r),&hhh),&ctx.mul(&FieldElem::from_num(2), &v));

        let rvx3 = ctx.mul(&r,&ctx.sub(&v,&x3));
        let s1hhh = ctx.mul(&s1,&hhh);

        let y3 = ctx.sub(&rvx3,&s1hhh);
        let z3 = ctx.mul(&p1.z, &ctx.mul(&p2.z, &h));
```
再次感谢您的耐心回复

**Comment by Pencil-Yao** [comment]
非常感谢你的优化测试，非常欢迎你为 `libsm` 提 issue 和 pr，关于性能测试最好在提供 bench 用例，例子如下
https://github.com/citahub/libsm/blob/66562196c3aa6a2f3db6fbf21e593521eadc2ae7/src/sm2/ecc.rs#L654-L668

**Comment by FullyRobert** [comment]
好的，非常感谢您的邀请，我会进行更详细的测试后再提交pr的。
另外，个人认为注释掉点加应该退化为点平方运算的相关语句的原因在于，每次判断两点是否相等的eq函数需要占用大量开销，远超使加法退化后产生的收益。这里我使用的是criterion进行的性能测试，测试结果表明eq函数的引入会使签名效率大幅下降：
```
Gnuplot not found, using plotters backend
sign                    time:   [758.40 us 768.05 us 780.96 us]                 
                        change: [+512.18% +531.20% +551.25%] (p = 0.00 < 0.05)
                        Performance has regressed.
```

**Comment by Pencil-Yao** [comment]
😂 `eq` 函数仅能作为 test 使用, 不能用于生产
