### ISSUE TITLE
sm2 add encrypt & decrypt function

### ISSUE THREAD

**Issue by Pencil-Yao** [citahub/libsm#23]

**Comment by ghost** [comment]
请问这个功能有进展吗，最近刚好用到这个。
谢谢

**Comment by Pencil-Yao** [comment]
暂时还不会开发

**Comment by vkill** [comment]
You can use [gmsm](https://docs.rs/gmsm/latest/gmsm/sm2/index.html)

**Comment by Pencil-Yao** [comment]
https://github.com/citahub/libsm/pull/36
