### ISSUE TITLE
sm2加解密时klen怎么设置？

### ISSUE THREAD

**Issue by gudaoxuri** [citahub/libsm#46]
https://github.com/citahub/libsm/blob/3ead619a180deb93474634584791b02561ca9a70/src/sm2/encrypt.rs#L142-L153

如上代码示例， 加解密时 `klen`  为要加密码信息的长度，我尝试使用固定值（E.g. 1024）会报错。 由于加密与解密可能在不同流程中使用，加密时可以知道原始数据的长度，但解密时只有密文，无法获取到原始数据的长度。请问要如何处理？

**Comment by luoffei** [comment]
加密后长度为原文长度加上97

**Comment by gudaoxuri** [comment]
> 加密后长度为原文长度加上97

Nice!
