### ISSUE TITLE
Add description of WebAssembly support

### ISSUE THREAD

**Issue by byeblack** [citahub/libsm#50]
You can use this crates in WebAssembly. Currently, you only need to add dependencies:
```toml
# Cargo.toml
getrandom = { version = "^0.2", features = ["js"] }
```
See [getrandom#WebAssembly support](https://docs.rs/getrandom/latest/getrandom/#webassembly-support).
But it still needs improvement for the first time #47

**Comment by Pencil-Yao** [comment]
nice suggestion https://github.com/citahub/libsm/pull/56
