### ISSUE TITLE
同样sm2签名和验签，为什么比go的慢了好多

### ISSUE THREAD

**Issue by nyrf** [citahub/libsm#55]
用github.com/tjfoc/gmsm/sm2 sm2签名和验签，用time看了下运行时间，发现libsm用的时间比go的多好多，而且在开发时，运行更慢。下面是release后的

```
❯ rustc --version
rustc 1.71.0-nightly (5cdb7886a 2023-04-15)
```

```
❯ go version
go version go1.18beta1 darwin/amd64
```

rust 的

```rust
    let msg = "test".as_bytes();
    let ctx = SigCtx::new();
    let (pk, sk) = ctx.new_keypair().unwrap();

    let signature = ctx.sign(&msg, &sk, &pk).unwrap();

    println!("signed is : {:?}", signature.to_string());
```

`cargo build --release`后运行，`time ./target/release/demo`看时间为

```
real	0m0.221s
user	0m0.216s
sys	0m0.003s
```

go 的

```go
package main

import (
	"crypto/rand"
	"fmt"
	"log"

	"github.com/tjfoc/gmsm/sm2"
)

func main() {
	priv, err := sm2.GenerateKey(rand.Reader) // 生成密钥对
	if err != nil {
		log.Fatal(err)
	}
	pub := &priv.PublicKey
	msg := []byte("test")
	sign, err := priv.Sign(rand.Reader, msg, nil) // sm2签名
	if err != nil {
		log.Fatal(err)
	}
	isok := pub.Verify(msg, sign) // sm2验签
	fmt.Printf("Verified: %v\n", isok)
}

```

`go build`后运行两次，`time ./demo`

```
Verified: true

real	0m0.370s
user	0m0.004s
sys	0m0.002s
```

```
Verified: true

real	0m0.009s
user	0m0.005s
sys	0m0.003s
```

可以看出go用的时间更少，而且go还做了加密解密两件事

**Comment by nyrf** [comment]
又试了下 https://github.com/Pencil-Yao/efficient-sm2 速度比GO 的还快点，这个也是依赖了libsm

```rust
use rand::RngCore;

fn main() {
    let test_word = b"hello world";

    let mut private_key = [0; 32];
    rand::thread_rng().fill_bytes(&mut private_key);

    let key_pair = efficient_sm2::KeyPair::new(&private_key).unwrap();

    // signing in sm2
    let sig = key_pair.sign(test_word).unwrap();

    // verification sm2 signature
    sig.verify(&key_pair.public_key(), test_word).unwrap();
}
```

```
real	0m0.010s
user	0m0.002s
sys	0m0.004s
```

**Comment by Pencil-Yao** [comment]
选择你喜欢用的就好了，想要寻找其中的答案，需要依赖你自身的数学能力和代码阅读能力，libsm是[efficient-sm2](https://github.com/Pencil-Yao/efficient-sm2)的老师或者父亲，但es2仅对sm2做出了优化，主要是数学层面的优化和增加缓存，这一点我在2020 rust大会 https://www.bilibili.com/video/BV1Yy4y1e7zR?p=8&vd_source=bbff00b55261776b479709cc8fec1d28 有过分享。关于与GO的区别，因为没有看过梧桐链做的密码库，所以我无法回答这个问题。

**Comment by nyrf** [comment]
> 选择你喜欢用的就好了，想要寻找其中的答案，需要依赖你自身的数学能力和代码阅读能力，libsm是[efficient-sm2](https://github.com/Pencil-Yao/efficient-sm2)的老师或者父亲，但es2仅对sm2做出了优化，主要是数学层面的优化和增加缓存，这一点我在2020 rust大会 https://www.bilibili.com/video/BV1Yy4y1e7zR?p=8&vd_source=bbff00b55261776b479709cc8fec1d28 有过分享。关于与GO的区别，因为没有看过梧桐链做的密码库，所以我无法回答这个问题。

谢谢，后面发现原来作者是都是你一个人的，用了es2, 感谢！
