### ISSUE TITLE
加密和解密代码可能是分开的klen 代码现实能不能去掉的，不然保存密文的时候还要多一个字段保存klen的

### ISSUE THREAD

**Issue by chenzhenpin** [citahub/libsm#60]

**Comment by Pencil-Yao** [comment]
首先你说的这块加解密是指基于 sm2 椭圆曲线的加解密？

**Comment by chenzhenpin** [comment]
是的，我只看到sm2这里的不知道其他地方有没有类似的

**Comment by Pencil-Yao** [comment]
不过现在这块没什么人手研究算法 我暂时也没时间做相关的工作
如果你可以对相关内容进行贡献，是非常欢迎的

另外我能给的建议只有：
1. 改用sm4加解密
2. 选择其他解决方案，应该说sm2加密也是很成熟的

**Comment by chenzhenpin** [comment]
多谢贡献，我对加密算法原理不了解，rust刚入门，刚好用到该库



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月27日(周三) 中午11:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [citahub/libsm] 加密和解密代码可能是分开的klen 代码现实能不能去掉的，不然保存密文的时候还要多一个字段保存klen的 (Issue #60)




 
不过现在这块没什么人手研究算法 我暂时也没时间做相关的工作
 如果你可以对相关内容进行贡献，是非常欢迎的
 
另外我能给的建议只有：
  
改用sm4加解密
 
选择其他解决方案，应该说sm2加密也是很成熟的
