### ISSUE TITLE
长度判断能不能提到verify()方法

### ISSUE THREAD

**Issue by chenzhenpin** [citahub/libsm#61]
pub fn verify_raw(&self, digest: &[u8], pk: &Point, sig: &Signature) -> Sm2Result<bool> {
        if digest.len() != 32 {
            return Err(Sm2Error::InvalidDigestLen);
        }

**Comment by Pencil-Yao** [comment]
我不太理解你的意思，事实上verify调用了verify_raw，具备长度判断

**Comment by chenzhenpin** [comment]
![image](https://github.com/citahub/libsm/assets/22683636/8774ee87-fb9e-4b0b-9c1e-e7ca1ae2b3a4)
我的意思是长度判断在verify()里面做，verify()和sign()对应，verify_raw和sign_raw()对应, 直接调用sign_raw(),但是又不想调用let digest = self.hash("1234567812345678", pk, msg)?;  用verify_raw 验签就不会报长度错误了
